esphome:
  name: esphome-web-ee65f8

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esphome_hotspot_ssid
    password: !secret esphome_hotspot_password

captive_portal:
    
sensor:
  - platform: adc
    pin: GPIO36
    attenuation: auto
    name: "Soil Moisture 1"
    unit_of_measurement: "%"
    device_class: humidity
    icon: "mdi:watering-can"
    filters:
      - calibrate_linear:
          - 2.89 -> 0
          - 1.46 -> 100
    update_interval: 5s
    accuracy_decimals: 0
  - platform: adc
    pin: GPIO36
    attenuation: auto
    name: "Soil Voltage 1"
    unit_of_measurement: "V"
    device_class: voltage
    update_interval: 5s
    accuracy_decimals: 2
